# Generated by Django 4.0.5 on 2022-08-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistermodel',
            name='student_otp',
            field=models.CharField(help_text='student_otp', max_length=18, null=True),
        ),
    ]
