# Generated by Django 4.0.5 on 2022-07-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransportfeedbackModel',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('vechicle_id', models.CharField(help_text='vechicle_id', max_length=230, null=True)),
                ('route', models.CharField(help_text='route', max_length=50, null=True)),
                ('tfeedback', models.CharField(help_text='tfeedback', max_length=50)),
                ('status', models.CharField(default='pending', help_text='status', max_length=50)),
                ('tstudent_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.studentregistermodel')),
            ],
            options={
                'db_table': 'studenttransportfeeback_details',
            },
        ),
        migrations.CreateModel(
            name='StudentHostelfeedbackModel',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(help_text='hostel_name', max_length=50)),
                ('hfeedback', models.CharField(help_text='hfeedback', max_length=50)),
                ('status', models.CharField(default='pending', help_text='status', max_length=50)),
                ('student_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.studentregistermodel')),
            ],
            options={
                'db_table': 'studenthostelfeeback_details',
            },
        ),
        migrations.CreateModel(
            name='StudentFacultyfeedbackModel',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(help_text='faculty_name', max_length=50)),
                ('faculty_subject', models.CharField(help_text='faculty_subject', max_length=20)),
                ('ffeedback', models.CharField(help_text='ffeedback', max_length=50)),
                ('status', models.CharField(default='pending', help_text='status', max_length=50)),
                ('fstudent_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.studentregistermodel')),
            ],
            options={
                'db_table': 'studentfacultyfeeback_details',
            },
        ),
    ]
