# Generated by Django 4.0.5 on 2022-07-14 06:56

from django.db import migrations, models
import email.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentfacultyfeedbackmodel_clarity_and_emphasis_on_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='passion_and_enthusiasm_to_teach',
            field=models.CharField(help_text='passion_and_enthusiasm_to_teach', max_length=20, null=True, verbose_name=email.encoders.encode_base64),
        ),
    ]
