# Generated by Django 4.0.5 on 2022-07-14 06:59

import _codecs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_studentfacultyfeedbackmodel_passion_and_enthusiasm_to_teach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='passion_and_enthusiasm_to_teach',
            field=models.CharField(help_text='passion_and_enthusiasm_to_teach', max_length=20, null=True, verbose_name=_codecs.utf_8_encode),
        ),
    ]
