# Generated by Django 4.0.5 on 2022-07-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('studentapp', '0004_alter_studentfacultyfeedbackmodel_passion_and_enthusiasm_to_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfacultyfeedbackmodel',
            name='facultys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.facultyregistermodel'),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='passion_and_enthusiasm_to_teach',
            field=models.CharField(help_text='passion_and_enthusiasm_to_teach', max_length=20, null=True),
        ),
    ]
