# Generated by Django 4.0.5 on 2022-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_alter_studentfacultyfeedbackmodel_clarity_and_emphasis_on_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='clarity_and_emphasis_on_concept',
            field=models.IntegerField(help_text='clarity_and_emphasis_on_concept', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='creating_interest_in_subject',
            field=models.IntegerField(help_text='creating_interest_in_subject', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='discipline_and_control_over_the_class',
            field=models.IntegerField(help_text='discipline_and_control_over_the_class', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='encouraging_and_student_interation',
            field=models.IntegerField(help_text='encouraging_and_student_interation', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='motivation_and_inspiration_the_student',
            field=models.IntegerField(help_text='motivation_and_inspiration_the_student', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='passion_and_enthusiasm_to_teach',
            field=models.IntegerField(help_text='passion_and_enthusiasm_to_teach', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='promoting_student_thinking',
            field=models.IntegerField(help_text='promoting_student_thinking', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='quality_of_illustrative_example',
            field=models.IntegerField(help_text='quality_of_illustrative_example', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='regularity_punctuality_and_uniform_coverage_of_syllabus',
            field=models.IntegerField(help_text='regularity_punctuality_and_uniform_coverage_of_syllabus', null=True),
        ),
        migrations.AlterField(
            model_name='studentfacultyfeedbackmodel',
            name='subject_knowledge',
            field=models.IntegerField(help_text='subject_knowledge', null=True),
        ),
    ]
